students =["Michio","Miki","Mikio","Minori","Minoru","Mitsuo","Mitsuru",
      "Nao","Naoki","Naoko","Noboru","Nobu","Nobuo","Nobuyuki","Nori",
      "Norio","Osamu","Rafu","Raiden","Ringo","Rokuro","Ronin","Ryo","Ryoichi",
      "Ryota","Ryozo","Ryuichi","Ryuu","Saburo","Sadao","Samuru",
      "Satoru","Satoshi","Seiichi","Seiji","Senichi","Shichiro","Shig",
      "Shigekazu","Shigeo","Shigeru","Shima","Shin","Shinichi","Shinji",
      "Shiro","Shoichi","Shoji","Shuichi","Shuji","Shunichi","Susumu",
      "Tadao","Tadashi","Takahiro","Takao","Takashi","Takayuki",
      "Takehiko","Takeo","Takeshi","Takeshi","Takumi","Tama","Tamotsu",
      "Taro","Tatsuo","Tatsuya","Teruo","Tetsip","Tetsuya","Tomi",
      "Tomio","Toru","Toshi","Toshiaki","Toshihiro","Toshio","Toshiyuki",
      "Toyo","Tsuneo","Tsutomu","Tsuyoshi","Uyeda","Yasahiro","Yasuhiro",
      "Yasuo","Yasushi","Yemon","Yogi","Yoichi","Yori","Yoshi",
      "Yoshiaki","Yoshihiro","Yoshikazu","Yoshimitsu","Yoshinori","Yoshio",
      "Yoshiro","Yoshito","Yoshiyuki","Yuichi","Yuji","Yuki"]